alias ..='cd ../'
alias ...='cd ../..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias addall='git add .'
alias clipboard='xclip -sel clip'
alias commit='git commit -m'
alias cp='cp -i'
alias df='df -h'
alias docker='sudo docker'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias free='free -m'
alias grep='grep --color=auto'
alias l.='exa -laF --icons --color=always --group-directories-first --ignore-glob=[A-Za-z0-9]*'
alias la='exa -laF --icons --color=always --group-directories-first'
alias ll='exa -lF --icons --color=always --group-directories-first'
alias ls='exa  -aF  --icons --color=always --group-directories-first'
alias lt='exa -T --icons --color=always --group-directories-first'
alias ltt='lt --level'
alias nitch='clear; nitch'
alias pacman='sudo pacman'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
alias pull='git pull origin'
alias push='git push origin'
alias status='git status'
alias tobash='sudo chsh mabushelbaia -s /bin/bash && echo '\''Log out!'\'''
alias tozsh='sudo chsh mabushelbaia -s /bin/zsh && echo '\''Log out!'\'''
alias gh='history|grep'
