format = """\
[╭╴](238)\
$all[╰─](238)$character"""
[c]
format = "[$symbol($version )]($style)"
disabled = true

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[battery]
disabled = true
[character]
success_symbol = "[](purple)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"
disabled = true
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

